### ISSUE TITLE
回调方法读取摄像头拍摄图片问题

### ISSUE THREAD

**Issue by krupp** [smallevilbeast/wxwork_pc_api#1]
您好，项目中接收消息的回调方法。我在接收摄像头拍摄的图片的信息的时候有个报错。读取到回调信息后我对图片有个读取的操作。这个时候会报图片不存在。
```python
        if message_type == MessageType.MT_RECV_IMG_MSG:
            print("为图片消息")
            file_path = message_data['file_path']
            with open(file_path, 'rb') as f:
                file_path = f.read()
                image_base64 = str(base64.b64encode(file_path), encoding='utf8')
```
报错信息如下
`
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "G:\wxwork\wxwork_pc_api\samples\python\wxwork.py", line 107, in wxwork_r
ecv_callback
    func(client_id, dict_data['type'], dict_data['data'])
  File "demo.py", line 54, in on_message
    with open(file_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\Docum
ents\\WXWork\\1688851911934285\\Cache\\Image\\2020-10\\a2b9adda5a8c4d49e14f4d90c
09d432c.jpg'
`

**Comment by smallevilbeast** [comment]
好的 我试试

**Comment by krupp** [comment]
@smallevilbeast 问题已经查清楚。原因是企业微信在保存图片的时候保存格式为jpg。而数据传输的过程中的图片格式是原始格式，辛苦了
