### ISSUE TITLE
请问一下是不能使用了么

### ISSUE THREAD

**Issue by Jw0160** [smallevilbeast/wxwork_pc_api#10]
![image](https://user-images.githubusercontent.com/19901452/167058132-f015fe1d-85a7-4305-a661-97e96f0be351.png)
只能收到启动和二维码的信息类型的回调
其他的消息没有回调 ---- (登录,收到消息)

**Comment by zhanghaofei** [comment]
就是啊，上周还用，这几天突然就不能了

**Comment by leavenow** [comment]
看起来确实是很久没有更新了。

**Comment by brucelian** [comment]
我也是最近一两周发现无法正常接收消息了

**Comment by Guo-yupo** [comment]
检测退出登录的接口怎么用啊
